Repository anassalam/TeamRankings, pull requests merged in 2021-10, with the labels that each got.

#1 tag Hacktoberfest2021
  code.py
Labels: Hacktoberfest

#23 write into file
  code.py
Labels: Hacktoberfest, Hacktoberfest2021, hacktoberfest-accepted

#24 code update
  code.py
Labels: Hacktoberfest, Hacktoberfest2021, hacktoberfest-accepted

#25 import json
  code.py
Labels: hacktoberfest-accepted

#27 parse
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#28 code updated
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#29 players in list
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#30 re-word assignments
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#32 code update
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#35 append and print
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#38 index matching
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#40 used numpy
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#41 numpy, matplot, pyplot, seaborn libraries added
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#42 rotate labels on x-axis
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#44 plot graph + save into jpg
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#46 array
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#52 code updated
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#53 array asserted
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#54 random number list
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#55 random number between given range
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#57 color dictionary
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#58 dumping
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#60 nested dictionary
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted

#62 printed nested dictionary n dumped into json file
  code.py
Labels: Hacktoberfest, hacktoberfest-accepted
